quarkus.http.port=10001
quarkus.langchain4j.mcp.weather.transport-type=stdio
quarkus.langchain4j.mcp.weather.command=uv,--directory,mcp,run,china_weather_mcp.py
quarkus.langchain4j.openai.base-url=https://api.deepseek.com
quarkus.langchain4j.openai.api-key=${DEEPSEEK_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=deepseek-chat
